spring.application.name=app-horario

# Puerto del Backend
server.port=8081

# --- CONFIGURACION DE BASE DE DATOS (DOCKER REMOTO) ---
spring.datasource.url=jdbc:mariadb://94.143.141.29:3307/app-horario
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace

# --- INICIALIZACION DE DATOS (data.sql) ---
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# SEGURIDAD JWT
jwt.secretKey=XXXYYY