spring.application.name=app-horario

# Puerto del Backend
server.port=8081

# --- CONFIGURACION DE BASE DE DATOS (DOCKER REMOTO) ---
spring.datasource.url=jdbc:mariadb://94.143.141.29:3307/app-horario
spring.datasource.username=admin_horario
spring.datasource.password=#jO22rA11mE3
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# --- OPTIMIZACION DE LOGS (Modo Silencioso) ---
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO

# --- OPTIMIZACION DE VELOCIDAD (Batch Fetching) ---
spring.jpa.properties.hibernate.default_batch_fetch_size=200
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# --- INICIALIZACION DE DATOS ---
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# SEGURIDAD JWT.
jwt.secretKey=XXXYYY

# --- CACHE DE SEGUNDO NIVEL (L2 Cache) ---
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
spring.jpa.properties.hibernate.generate_statistics=false